# Generated by Django 3.2.16 on 2024-05-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20240514_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blogicum_images', verbose_name='Изображение'),
        ),
    ]
